### ISSUE TITLE
关于自动播放

### ISSUE THREAD

**Issue by wangxiaochuan366** [tjuking/audio.js#1]
博主 你好，我有注意到你在document上绑定了 touch事件   我这边是在用户不触摸屏幕的情况下自动播放音乐 尝试了模拟触摸但是没有成功，求指点一二。

**Comment by tjuking** [comment]
@wangxiaochuan366 无触摸播放之前也有尝试过，都没成功，因此这里只有用户第一次触摸屏幕的时候开始播放
